local BaseConfig = {
	BasesFolderName = "Bases",
	BaseSpawnPartName = "PlayerSpawn",
	BaseSlotsFolderName = "Slots",
	SlotCollectPartName = "CollectPart",
	CapturedNPCFolderName = "CapturedNPCs",
	TeleportToAssignedBaseOnCharacterAdded = true,
	CharacterSpawnYOffset = 3,
	CollectionDebounceSeconds = 0.35,
	CollectionPerPartCooldownSeconds = 2,
	Currency = {
		LeaderstatsFolderName = "leaderstats",
		StatName = "Money",
		CreateIfMissing = true,
	},
	Income = {
		DefaultIncomePerSecond = 1,
		TickIntervalSeconds = 1,
		SlotEmptyAmountText = "$0",
		SlotAmountPrefix = "$",
	},
	OwnedNPCDisplay = {
		TemplatePath = { "ReplicatedStorage", "NPCSystem", "DisplayTemplates", "OwnedNPCDisplay" },
		StudsOffset = Vector3.new(0, 2.5, 0),
		Size = UDim2.new(0, 300, 0, 120),
		AlwaysOnTop = true,
		LightInfluence = 0,
		MaxDistance = 500,
		SizeOffset = Vector2.zero,
		ExtentsOffset = Vector3.zero,
		ExtentsOffsetWorldSpace = Vector3.zero,
	},
	OwnedCarry = {
		GrabPromptName = "Grab",
		GrabActionText = "Grab",
		GrabObjectText = "Grab",
		GrabKeyboardKeyCode = Enum.KeyCode.E,
		GrabMaxActivationDistance = 8,
		GrabRequiresLineOfSight = false,
		GrabUIOffset = Vector2.new(0, 36),
		PlacePromptName = "Place",
		PlaceActionText = "Place",
		PlaceObjectText = "Target Slot",
		PlaceKeyboardKeyCode = Enum.KeyCode.E,
		PlaceMaxActivationDistance = 8,
		PlaceRequiresLineOfSight = false,
		PlaceUIOffset = Vector2.new(0, 0),
		DeleteUIOffsetWhenGrabEnabled = Vector2.new(0, -36),
		CarryForwardDistance = 3,
		CarryUpOffset = 1.75,
		EnablePlacePromptOnlyWhileCarrying = true,
	},
	CarryRestrictions = {
		CarryModeAttributeName = "BrainrotCarryMode",
		ToolsLockedAttributeName = "BrainrotCarryToolsLocked",
		OwnedPlacePromptActiveAttributeName = "OwnedBrainrotPlacePromptActive",
		TemporaryCarryWalkSpeedMultiplier = 0.9,
	},
	DeletePrompt = {
		ActionText = "Delete",
		ObjectText = "Delete",
		KeyboardKeyCode = Enum.KeyCode.X,
		HoldDuration = 3,
		MaxActivationDistance = 8,
		RequiresLineOfSight = false,
		UIOffset = Vector2.new(0, 0),
	},
	Remotes = {
		CollectionFeedbackEventName = "CollectionFeedback",
		CapturePromptEventName = "CapturePrompt",
		CaptureDecisionEventName = "CaptureDecision",
		MoneySnapshotFunctionName = "MoneySnapshot",
		CapturableCarryStateEventName = "CapturableCarryState",
		CapturableDropRequestEventName = "CapturableDropRequest",
		CapturableLifecycleEventName = "CapturableLifecycle",
	},
	CollectionFeedback = {
		VFXTemplatePath = { "ReplicatedStorage", "NPCSystem", "ClientAssets", "CollectionVFX" },
		SoundTemplatePath = { "ReplicatedStorage", "NPCSystem", "ClientAssets", "CollectionSFX" },
		VFXLifetimeSeconds = 2,
		SoundLifetimeSeconds = 4,
	},
	UI = {
		MoneyLabelPath = { "MoneyIndicator", "MoneyFrame", "MoneyLabel" },
		CapturePromptGuiPath = { "QuestionGui" },
		CapturePromptFrameName = "QuestionFrame",
		CapturePromptTextLabelName = "Text",
		CaptureYesButtonName = "Yes",
		CaptureNoButtonName = "No",
		NoFreeSlotsGuiPath = { "SlotWarningGui" },
		NoFreeSlotsLabelName = "SlotWarningLabel",
		NoFreeSlotsText = "No free slots",
		NoFreeSlotsFadeInSeconds = 0.2,
		NoFreeSlotsHoldSeconds = 1.2,
		NoFreeSlotsFadeOutSeconds = 0.25,
		CapturePromptTemplate = "You wanna put \"%s\" in your base?",
		CapturableDropButtonName = "CapturableDropButton",
	},
	CaptureFlow = {
		PendingTimeoutSeconds = 12,
		DefeatedRespawnDelaySeconds = 2,
		RedeemPartName = "BrainrotRedeemPart",
		RedeemTouchDebounceSeconds = 1,
		DefeatedBillboardTemplatePath = { "ReplicatedStorage", "NPCSystem", "DisplayTemplates", "DefeatGui" },
		DefeatedVFXTemplatePath = { "ReplicatedStorage", "NPCSystem", "ClientAssets", "DefeatedVFX" },
		DefeatedSFXTemplatePath = { "ReplicatedStorage", "NPCSystem", "ClientAssets", "DefeatedSFX" },
	},
	Persistence = {
		DataStoreName = "NPCBasePrototype_v1",
		KeyPrefix = "Player_",
		MaxRetries = 5,
		InitialBackoffSeconds = 0.5,
		SaveDebounceSeconds = 2,
		ShutdownSaveTimeoutSeconds = 20,
	},
}

return BaseConfig
