local NPCSpawnConfig = {
	SpawnPointTag = "NPCSpawnPoint",
	SpawnPointFolderName = "NPCSpawnPoints",
	SpawnPointNameFallback = "NPCSpawnPoint",
	EnableNameBasedSpawnPointFallback = true,
	SpawnCooldownSeconds = 30,
	BlockedSpawnRetrySeconds = 2,
	FailedSpawnRetrySeconds = 5,
	TemplateFolderPath = { "ReplicatedStorage", "NPCs", "Templates" },
	WorldNPCDisplayTemplatePath = { "ReplicatedStorage", "NPCSystem", "DisplayTemplates", "WorldNPCDisplay" },
	WorldNPCDisplay = {
		StudsOffset = Vector3.new(0, 2.5, 0),
		Size = UDim2.new(0, 300, 0, 120),
		AlwaysOnTop = true,
		LightInfluence = 0,
		MaxDistance = 500,
		SizeOffset = Vector2.zero,
		ExtentsOffset = Vector3.zero,
		ExtentsOffsetWorldSpace = Vector3.zero,
	},

	WorldNPCDisplayStudsOffset = Vector3.new(0, 2.5, 0),
	WorldNPCDisplaySize = UDim2.new(0, 300, 0, 120),
	WorldNPCDisplayAlwaysOnTop = true,
	WorldNPCDisplayLightInfluence = 0,
	WorldNPCDisplayMaxDistance = 500,
	NPCContainerName = "SpawnedNPCs",
	EnableDebugWarnings = false,
	Lifetime = {
		DefaultAliveLifetimeSeconds = 60,
		TimerUpdateIntervalSeconds = 0.1,
		TimerDecimalPlaces = 1,
	},
	InitialFill = {
		Enabled = true,
		TotalDurationSeconds = 45,
		FirstSpawnDelaySeconds = 0,
	},
	Damage = {
		DefaultToolDamage = 10,
		MaxHitDistance = 20,
		DefaultHitboxSize = Vector3.new(6, 6, 8),
		DefaultPlayerHitboxSize = Vector3.new(8, 6, 9),
		ToolUseCooldownSeconds = 0.25,
		PerTargetHitCooldownSeconds = 0.12,
		RemoteEventName = "RequestNPCDamage",
	},
	ProximityIndicator = {
		Enabled = true,
		ShowDistance = 22,
		HideDistance = 25,
		RingRadius = 8,
		HeightOffset = 0.08,
		SegmentCount = 28,
		SegmentLength = 1.0,
		SegmentThickness = 0.16,
		SegmentHeight = 0.08,
		Color = Color3.fromRGB(255, 255, 255),
		HiddenTransparency = 1,
		VisibleTransparency = 0.15,
		TweenInTime = 0.12,
		TweenOutTime = 0.14,
		ScaleInFrom = 0.94,
		UpdateIntervalSeconds = 0.1,
		DefaultAttackRadius = 8,
		RadiusHysteresisBuffer = 1.2,
	},
}

return NPCSpawnConfig
