local OwnedNPCLevelConfig = {
	LevelIncomeMultiplier = 1.10,
	UpgradeCostMultiplier = 1.50,
	DefaultLevel = 1,
	MaxLevel = 100,
	MinimumUpgradeCost = 1,
	UpgradePartName = "UpgradePart",
	UpgradeGuiName = "UpgradeGui",
	UpgradeButtonName = "Button",
	UpgradeCostLabelName = "Cost",
	UpgradeLevelChangeLabelName = "LevelChange",
	EmptyCostText = "$0",
	EmptyLevelChangeText = "Level -",
	MaxCostText = "MAX",
	MaxLevelChangeTextTemplate = "Level %d > MAX",
	CurrencyPrefix = "$",
	RemoteEventName = "OwnedNPCUpgradeRequest",
	UpgradeFeedbackRemoteEventName = "OwnedNPCUpgradeFeedback",
	InsufficientFundsLabelPath = { "InsufficientFundsGui", "InsufficientFundsLabel" },
	InsufficientFundsTextTemplate = "Insufficient funds, cost: %s",
	InsufficientFundsLabelShowSeconds = 1.2,
	MaxLevelLabelPath = { "MaxLevelGui", "MaxLevelLabel" },
	MaxLevelTextTemplate = "This brainrot is already at the maximum level (%d).",
	MaxLevelLabelShowSeconds = 1.2,
	InsufficientFundsSFXPath = { "ReplicatedStorage", "NPCSystem", "ClientAssets", "UpgradeInsufficientSFX" },
	UpgradeSuccessSFXPath = { "ReplicatedStorage", "NPCSystem", "ClientAssets", "UpgradeSuccessSFX" },
	InsufficientFundsSFXCooldownSeconds = 1,
	DebugLogs = true,
}

return OwnedNPCLevelConfig
