local WeaponShopConfig = {
	CycleDurationSeconds = 600,
	CycleEpochUnix = 1_700_000_000,
	StockRollSalt = 91357,
	StockRefreshPollSeconds = 1,
	EnableDebugWarnings = false,
	OutOfStockFeedbackLabelPath = { "Shop", "ItemShop", "OutOfStockLabel" },
	OutOfStockFeedbackText = "OUT OF STOCK",
	OutOfStockFeedbackDurationSeconds = 1.5,
	OutOfStockSFXPath = { "ReplicatedStorage", "NPCSystem", "ClientAssets", "UpgradeInsufficientSFX" },
	OutOfStockSFXCooldownSeconds = 0.25,
	SuccessSFXPath = { "ReplicatedStorage", "NPCSystem", "ClientAssets", "UpgradeSuccessSFX" },
	SuccessSFXCooldownSeconds = 0.1,
	InsufficientMoneyFeedbackLabelPath = { "Shop", "ItemShop", "InsufficientMoneyLabel" },
	InsufficientMoneyFeedbackText = "NOT ENOUGH MONEY",
	InsufficientMoneyFeedbackDurationSeconds = 1.5,
	UseGamePassPurchase = false,
	ToolsFolderPath = { "ReplicatedStorage", "WeaponShop", "Tools" },
	OwnershipDataStoreName = "WeaponShopOwnership_v1",
	OwnershipDataKeyPrefix = "Player_",
	MaxSaveRetries = 5,
	InitialBackoffSeconds = 0.5,
	SaveDebounceSeconds = 2,
	ShutdownSaveTimeoutSeconds = 20,
	ManagedToolAttribute = "ShopManagedWeapon",
	ManagedToolWeaponIdAttribute = "ShopWeaponId",
	CombatToolAttribute = "NPCCombatTool",
	RemotesFolderPath = { "ReplicatedStorage", "WeaponShop", "Remotes" },
	Remotes = {
		RequestShopStateFunctionName = "RequestShopState",
		PurchaseWeaponEventName = "PurchaseWeapon",
		RequestEquipWeaponEventName = "RequestEquipWeapon",
		RequestRobuxPurchaseEventName = "RequestRobuxPurchase",
		ShopStateUpdatedEventName = "ShopStateUpdated",
		PurchaseResultEventName = "PurchaseResult",
	},
	Weapons = {
		{
			Id = "SteelSword",
			DisplayName = "Steel Sword",
			ToolNameInReplicatedStorage = "SteelSword",
			Price = 500,
			Icon = "rbxassetid://0",
			RarityId = "Common",
			StockMin = 1,
			StockMax = 5,
			StockAppearanceChancePercent = 100,
			RobuxProductId = 0,
			GamePassId = 0,
			Enabled = true,
			LoadoutSlot = "Extra",
			Damage = 14,
			AttackRange = 10,
			AttackHitboxSize = Vector3.new(7, 6, 8),
			PlayerHitboxSize = Vector3.new(10, 7, 11),
			CanDamagePlayers = false,
			CanCoexistWithEquippedWeapon = true,
			ContestDisarmEnabled = true,
			KnockbackHorizontal = 58,
			KnockbackVertical = 20,
		},
		{
			Id = "KnightBlade",
			DisplayName = "Knight Blade",
			ToolNameInReplicatedStorage = "KnightBlade",
			Price = 2500,
			Icon = "rbxassetid://0",
			RarityId = "Rare",
			StockMin = 1,
			StockMax = 3,
			StockAppearanceChancePercent = 35,
			RobuxProductId = 0,
			GamePassId = 0,
			Enabled = true,
			LoadoutSlot = "Primary",
			Damage = 20,
			AttackRange = 11,
			AttackHitboxSize = Vector3.new(8, 6, 9),
			PlayerHitboxSize = Vector3.new(8, 6, 9),
			CanDamagePlayers = false,
			CanCoexistWithEquippedWeapon = false,
			ContestDisarmEnabled = false,
			KnockbackHorizontal = 0,
			KnockbackVertical = 0,
		},
		{
			Id = "Sunbreaker",
			DisplayName = "Sunbreaker",
			ToolNameInReplicatedStorage = "Sunbreaker",
			Price = 10000,
			Icon = "rbxassetid://0",
			RarityId = "Legendary",
			StockMin = 1,
			StockMax = 2,
			StockAppearanceChancePercent = 0.5,
			RobuxProductId = 0,
			GamePassId = 0,
			Enabled = true,
			LoadoutSlot = "Primary",
			Damage = 28,
			AttackRange = 12,
			AttackHitboxSize = Vector3.new(9, 6.5, 10),
			PlayerHitboxSize = Vector3.new(9, 6.5, 10),
			CanDamagePlayers = false,
			CanCoexistWithEquippedWeapon = false,
			ContestDisarmEnabled = false,
			KnockbackHorizontal = 0,
			KnockbackVertical = 0,
		},
	},
}

return WeaponShopConfig
